// Import Bunosh functions from global object
const { exec, fetch, writeToFile, say, yell } = global.bunosh;
const fs = require('fs');
const path = require('path');
const { globSync } = require('glob');

require('dotenv').config();

const token = process.env.GH_PAT;

const FETCH_ISSUES_REQUEST = 'GET /repos/{owner}/{repo}/issues?labels={label}&sort=comments&direction=desc'

const humanize = (s) => s.replace(/-([a-z])/g, (_, c) => ' ' + c.toUpperCase()).replace(/^([a-z])/, (_, c) => c.toUpperCase());
const slugify = require('slugify')
const dasherize = (str) => slugify(str.toLowerCase());

// Frontmatter templates for documentation files
const JS_FRONTMATTER = `---
title: Import JavaScript Tests
description: Import JavaScript tests into Testomat.io using the CLI tool with support for various frameworks like Cypress, TestCafe, and Protractor. This guide covers commands for importing, synchronizing, and managing test IDs, as well as options for handling parametrized tests, disabling detached tests, and importing into specific suites or branches.
type: article
url: https://docs.testomat.io/project/import-export/import-js
head:
  - tag: meta
    attrs:
      name: og:image
      content: https://user-images.githubusercontent.com/24666922/78563263-505d1280-7838-11ea-8fbc-18e942d48485.png

  - tag: meta
    attrs:
      name: keywords
      content: Testomat.io, JavaScript test import, automated tests, test management, CLI tool, test synchronization, parametrized tests, Test IDs, Cypress, TestCafe, Protractor, QA tools
---

<!-- DO NOT EDIT THIS FILE DIRECTLY. IT IS GENERATED FROM open-source project https://github.com/testomatio/check-tests -->

Testomat.io can import automated tests into a project.
We provide CLI tools for different frameworks so you get visibility of your tests in seconds.
On this page we collect the reference to them. Learn how to install and configure test importer for your project.

## JavaScript

> 📑 This documentation is taken from open-source project [testomatio/check-tests](https://github.com/testomatio/check-tests)`;

const PHP_FRONTMATTER = `---
title: Import PHP Tests
description: Import PHP tests into Testomat.io using the list-tests CLI utility, which supports PHPUnit and Codeception. This guide explains how to install the tool, print and export test lists in markdown format, and import tests directly into Testomat.io by passing the API key for your project. Easily manage PHP tests and maintain live documentation with this integration.
type: article
url: https://docs.testomat.io/project/import-export/import-php
head:
  - tag: meta
    attrs:
      name: og:image
      content: https://docs.testomat.io/_astro/test-reporting-heat-map.CoE-TwPN_Z20qVi.webp

  - tag: meta
    attrs:
      name: keywords
      content: Testomat.io, PHP test import, PHPUnit, Codeception, CLI tool, test management, live documentation, markdown export, test synchronization, API key, QA tools
---

<!-- DO NOT EDIT THIS FILE DIRECTLY. IT IS GENERATED FROM open-source project https://github.com/testomatio/php-list-tests -->

> 📑 This documentation is taken from open-source project [testomatio/php-list-tests](https://github.com/testomatio/php-list-tests)`;

const BDD_FRONTMATTER = `---
title: Import Cucumber BDD Tests
description: Import Cucumber BDD tests into Testomat.io using the check-cucumber CLI tool. This guide covers commands to synchronize tests, assign test IDs, manage detached tests, and clean or import tests into specific suites, branches, or keep source code structure intact. It also supports both manual and automated BDD test imports, allowing efficient test management and version control.
type: article
url: https://docs.testomat.io/project/import-export/import-bdd
head:
  - tag: meta
    attrs:
      name: og:image
      content: https://user-images.githubusercontent.com/24666922/78559548-2dc7fb00-7832-11ea-8c69-0722222a82fe.png

  - tag: meta
    attrs:
      name: keywords
      content: Testomat.io, Cucumber BDD, CLI tool, test import, test IDs, test synchronization, automated tests, manual tests, test management, QA tools
---

<!-- DO NOT EDIT THIS FILE DIRECTLY. IT IS GENERATED FROM open-source project https://github.com/testomatio/check-cucumber](https://github.com/testomatio/check-cucumber) -->

> 📑 This documentation is taken from open-source project [testomatio/check-cucumber](https://github.com/testomatio/check-cucumber)`;

/**
 * Main docs task that imports and processes documentation
 */
export async function docs() {
  await docsImporter();
  await docsReporter();
}

/**
 * Process images in documentation files
 */
export async function docsImages() {
  const files = globSync("src/content/docs/**/*.md");

  for (const file of files) {
    say(`Processing ${file}`);
    const content = fs.readFileSync(file).toString();

    const destinationFolder = path.join(path.dirname(file), 'images');

    if (!fs.existsSync(destinationFolder)) {
      fs.mkdirSync(destinationFolder, { recursive: true });
    }

    const imageUrls = content.match(/!\[.*?\]\((.*?)\)/g)?.map(match => match.match(/!\[.*?\]\((.*?)\)/)[1]) || [];
    console.log(imageUrls);

    let updatedContent = content;

    if (!imageUrls.length) continue;

    for (const imageUrl of imageUrls) {
      if (imageUrl.startsWith('http')) {
        try {
          await downloadImage(imageUrl, destinationFolder);
          updatedContent = updatedContent.replace(imageUrl, `./images/${path.basename(imageUrl)}`);
        } catch (err) {}
        continue;
      }
      // try {
      //   fs.renameSync(path.join('docs/.vuepress/public', imageUrl), path.join(destinationFolder, path.basename(imageUrl)), { overwrite: true });
      // } catch (err) {}
      updatedContent = updatedContent.replace(imageUrl, `./images/${path.basename(imageUrl)}`);
    }

    // updatedContent = content.replace(/!\[.*?\]\((\/assets\/.*?)\)/g, "![$&](images$1)");

    // console.log(updatedContent);
    fs.writeFileSync(file, updatedContent);
  }
}

/**
 * Generate and process reporter documentation
 */
export async function docsReporter() {
  await exec`rm -rf tmp/reporter`;
  await exec`rm -rf tmp/php-reporter`;
  await exec`rm -rf tmp/pytest-reporter`;

  const destinationFolder = path.resolve(path.join(__dirname, 'src/content/docs/test-reporting'));

  say(`Destination folder: ${destinationFolder}`);

  if (!fs.existsSync(destinationFolder)) {
    fs.mkdirSync(destinationFolder, { recursive: true });
  }

  // saving headers of files
  const files = globSync(`${destinationFolder}/**/*.md`);

  let fileHeaders = {}
  for (const file of files) {
    const content = fs.readFileSync(file, 'utf8');
    const match = content.match(/^---[\s\S]+?^---/m);
    if (match) {
      fileHeaders[path.basename(file, '.md')] = match[0];
    }
  }

  await exec`git clone https://github.com/testomatio/reporter.git tmp/reporter --depth=1`;

  // Copy docs files using Node.js fs instead of cp command
  const docsSrc = path.join(__dirname, 'tmp/reporter/docs');
  const docsFiles = fs.readdirSync(docsSrc);
  for (const file of docsFiles) {
    const srcPath = path.join(docsSrc, file);
    const destPath = path.join(destinationFolder, file);
    if (fs.statSync(srcPath).isFile()) {
      fs.copyFileSync(srcPath, destPath);
    }
  }

  const phpReporterUrl = 'https://github.com/testomatio/php-reporter'
  await exec`git clone ${phpReporterUrl}.git tmp/php-reporter --depth=1`;
  const phpReadme = 'tmp/php-reporter/README.md';

  const pytestReporterUrl = 'https://github.com/testomatio/pytestomatio'
  await exec`git clone ${pytestReporterUrl}.git tmp/pytest-reporter --depth=1`;
  const pytestReadme = 'tmp/pytest-reporter/README.md';

  const capitalize = s => s && s[0].toUpperCase() + s.slice(1)

  const filesToDelete = ['pipes', 'debugging', 'stacktrace']
  for (const file of filesToDelete) {
    say(`Deleting pipes file: ${file}`);
    try {
      fs.unlinkSync(path.join(destinationFolder, file + '.md'));
    } catch (error) {
      // console.error(`Error deleting file ${file}: ${error.message}`);
    }
  }

  const updatedFiles = globSync(`${destinationFolder}/**/*.md`);
  for (const file of updatedFiles) {
    if (['index', 'php', 'python'].includes(path.basename(file, '.md'))) continue;
    let title = humanize(path.basename(file, '.md')).trim();
    if (title.length > 0) {
      title = title.charAt(0).toUpperCase() + title.slice(1);
    }
    const titleId = title.toUpperCase();

    if (titleId === 'FRAMEWORKS') title = "NodeJS Test Frameworks";
    if (titleId === 'TESTOMATIO') title = "Advanced Options"
    if (titleId === 'JUNIT') title = "JUnit Reporter"
    let contents;
    try {
      contents = fs.readFileSync(file).toString()
    } catch (error) {
      continue;
    }

    // Check if content already has the correct frontmatter
    const hasCorrectFrontmatter = contents.startsWith('---\ntitle: ');

    // Skip processing if file already has correct frontmatter
    if (hasCorrectFrontmatter && fileHeaders[path.basename(file, '.md')]) {
      continue;
    }

    // Extract existing frontmatter if it exists
    let existingFrontmatter = '';
    const frontmatterMatch = contents.match(/^---[\s\S]*?^---\n/m);
    if (frontmatterMatch) {
      existingFrontmatter = frontmatterMatch[0];
    }

    // Remove existing frontmatter from content
    contents = contents.replace(/^---[\s\S]*?^---\n/m, '');

    contents = contents.replace(/^#\s.+/gm, '');
    // fix links
    // contents = transformLinks(contents)

    // Use existing frontmatter if available, otherwise use stored or generate new
    const frontmatter = existingFrontmatter ||
                       fileHeaders[path.basename(file, '.md')] ||
                       `---\ntitle: ${title}\n---`;

    contents = `${frontmatter}\n${contents}\n`;

    fs.writeFileSync(file, contents)
  }

  let phpContents = fs.readFileSync(phpReadme).toString().replace(/^#\s.+/gm, '');
  phpContents = phpContents.replace(/^---[\s\S]+?^---/m, '');
  phpContents = phpContents.replace(/^#\s.+/gm, '');
  phpContents = `\n\n:::note\n Taken from [PHP Reporter Readme](${phpReporterUrl})\n:::\n ${phpContents}\n`

  fs.writeFileSync(path.join(destinationFolder, '/php.md'), fileHeaders.php + phpContents)

  let pytestContents = fs.readFileSync(pytestReadme).toString().split('## Change')[0];
  pytestContents = pytestContents.replace(/^---[\s\S]+?^---/m, '');
  pytestContents = `\n\n:::note\n Taken from [Pytestomatio Reporter Readme](${pytestReporterUrl})\n:::\n\n${pytestContents}\n`

  fs.writeFileSync(path.join(destinationFolder, '/python.md'), fileHeaders.python + pytestContents)
  // writeToFile(destinationFolder + '/python.md', cfg => {
  //   cfg.line(fileHeaders.python || '---\nPython Reporter\n---');
  //   cfg.line(pytestContents);
  // });
}

/**
 * Import documentation from various sources
 */
export async function docsImporter() {
  const destinationFolder = 'src/content/docs/project/import-export';

  if (!fs.existsSync(destinationFolder)) {
    fs.mkdirSync(destinationFolder, { recursive: true });
  }

  const response = await fetch('https://raw.githubusercontent.com/testomatio/check-tests/master/README.md');
  let content = response.output;
  content = content.split('\n');
  content = content.slice(content.indexOf('## CLI') + 2).join('\n').replace(/#\s/g, '## ')

  writeToFile('src/content/docs/project/import-export/import/import-js.md', (line) => {
    line(JS_FRONTMATTER);
    line('');
    line(content);
  });

  const response2 = await fetch('https://raw.githubusercontent.com/testomatio/php-list-tests/0.2.x/README.md');
  let content2 = response2.output;
  content2 = content2.split('\n').slice(3).join('\n').replace(/#\s/g, '## ')


  writeToFile('src/content/docs/project/import-export/import/import-php.md', (line) => {
    line(PHP_FRONTMATTER);
    line('');
    line(content2);
  });

  const response3 = await fetch('https://raw.githubusercontent.com/testomatio/check-cucumber/master/README.md');
  let content3 = response3.output.split('\n');
  content3 = content3.slice(content3.indexOf('## Cli') + 2).join('\n')


  writeToFile('src/content/docs/project/import-export/import/import-bdd.md', (line) => {
    line(BDD_FRONTMATTER);
    line('');
    line(content3);
  });
}

async function downloadImage(imageUrl, destinationFolder) {
  try {
    const img = imageUrl.split('/')[imageUrl.split('/').length - 1];

    if (fs.existsSync(path.join(destinationFolder, img))) {
      say(`Image already exists: ${imageUrl}`);
      return path.join(destinationFolder, img);
    }

    const response = await fetch(imageUrl);
    // Bunosh fetch returns TaskResult with output containing the binary data
    const imageData = response.output;

    // Extract content type from response if available, otherwise use fallback
    let contentType = 'image/jpeg'; // fallback
    if (response.headers && response.headers['content-type']) {
      contentType = response.headers['content-type'];
    }

    const extension = contentType.split('/')[1];

    if (!fs.existsSync(destinationFolder)) {
      fs.mkdirSync(destinationFolder, { recursive: true });
    }

    const filename = path.join(destinationFolder, img);
    fs.writeFileSync(filename, Buffer.from(imageData));

    say(`Downloaded image: ${imageUrl} => ${filename}`);
    return filename;
  } catch (error) {
    console.error(`Failed to download image: ${imageUrl} ${error}`);
    // process.exit(1);
    throw error;
    // return null;
  }
}
