name: Publish

on:
  push:
    branches:
      - docs
jobs:
  deploy:
    name: Build & Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 20.x
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      - run: pnpm install
      - run: pnpm run build
        env:
          PUBLIC_MEILISEARCH_KEY: ${{ secrets.PUBLIC_MEILISEARCH_KEY }}
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 60b76f40370d8320885e92e3daa114b1
          projectName: docs
          directory: dist

  run-scraper:
    needs: deploy
    name: Run Search Scraper
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Search Index
      env:
        HOST_URL: ${{ secrets.MEILISEARCH_HOST_URL }}
        API_KEY: ${{ secrets.MEILISEARCH_API_KEY }}
      run: |
        docker run -t --rm \
          -e MEILISEARCH_HOST_URL=$HOST_URL \
          -e MEILISEARCH_API_KEY=$API_KEY \
          -v $PWD/docsearch.json:/docs-scraper/docsearch.json \
          getmeili/docs-scraper:latest pipenv run ./docs_scraper docsearch.json
