name: Test build

on:
  pull_request:
    branches:
      - docs

jobs:
  deploy:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install bunosh
        run: bun add -g bunosh
      - run: bun install
      - run: bunosh docs
      - run: bun run build